repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: debug-statements

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        types: [python]
        args: [--cov=wry, --cov-report=xml, --cov-report=term-missing, --cov-fail-under=90]
        pass_filenames: false
        always_run: true
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        args: [wry/]
        pass_filenames: false

# Temporarily disabled - bandit has dependency issues in pre-commit
  # - repo: https://github.com/PyCQA/bandit
  #   rev: 1.7.5
  #   hooks:
  #     - id: bandit
  #       args: [-c, pyproject.toml]

exclude: |
  (?x)(
    # Exclude auto-generated files
    wry/_version\.py|
    # Exclude build artifacts
    dist/|
    build/|
    \.egg-info/
  )
